# Generated by Django 3.1.7 on 2021-03-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropriedadesPessoa',
            new_name='PropriedadePessoa',
        ),
    ]
