# Generated by Django 3.1.7 on 2021-03-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210328_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='apelido',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
