# Generated by Django 3.1.7 on 2021-03-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210328_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.FloatField(max_length=100, unique=True),
        ),
    ]
