# Generated by Django 3.1.7 on 2021-03-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210328_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
