# Generated by Django 3.1.7 on 2021-03-28 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210328_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='funcao',
            field=models.FloatField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='tag',
            name='pai',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
    ]
