# Generated by Django 3.1.7 on 2021-03-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210328_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='cor_hex',
            field=models.TextField(max_length=6),
        ),
        migrations.AlterField(
            model_name='tag',
            name='funcao',
            field=models.TextField(blank=True, max_length=6),
        ),
    ]
