# Generated by Django 3.1.7 on 2021-03-28 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210328_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
    ]
